// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.windows: return windows;
      default: throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM8XVM3XMf9e3RaL1mOMCPeX1qBan3KKY',
    appId: '1:62052744777:web:299ec46dbb412956900998',
    messagingSenderId: '62052744777',
    projectId: 'perfumes-da-mayar',
    authDomain: 'perfumes-da-mayar.firebaseapp.com',
    storageBucket: 'perfumes-da-mayar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51EVTfyf3rFXmOumc4Z6ToDwVs-uMUp4',
    appId: '1:62052744777:android:21c791e985a82102900998',
    messagingSenderId: '62052744777',
    projectId: 'perfumes-da-mayar',
    storageBucket: 'perfumes-da-mayar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6hnzcEwD90SvFQiH2eII8sdmMkIcd4k',
    appId: '1:62052744777:ios:60cafe40b6094336900998',
    messagingSenderId: '62052744777',
    projectId: 'perfumes-da-mayar',
    storageBucket: 'perfumes-da-mayar.firebasestorage.app',
    iosBundleId: 'com.example.projetoCatalogoDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM8XVM3XMf9e3RaL1mOMCPeX1qBan3KKY',
    appId: '1:62052744777:web:84f43dd11ee8f56e900998',
    messagingSenderId: '62052744777',
    projectId: 'perfumes-da-mayar',
    authDomain: 'perfumes-da-mayar.firebaseapp.com',
    storageBucket: 'perfumes-da-mayar.firebasestorage.app',
  );
}
